### PR TITLE
bug(nyan): nyan and directive template

### PR DESCRIPTION
**Pull request by judearasu**
nyan moved inside appstart and lowercase applied to render ctrlalias

@eduardogch  Validate the nyan change before publish :+1: 

Thanks

### CODE REVIEW

**Comment by eduardogch** [comment]
screenshot from 2016-04-02 11 26 12

This cat just become crazy!

**Comment by judearasu** [comment]
Ooh :(

**Comment by eduardogch** [comment]
Let's control that crazy cat with async functions, references:

https://github.com/caolan/async
http://webapplog.com/seven-things-you-should-stop-doing-with-node-js/

**Comment by judearasu** [comment]
Sure

On Sat, Apr 2, 2016 at 11:36 AM, Eduardo Gonzalez <notifications@github.com>
wrote:

> Let's control that crazy cat with async functions, references:
>
> https://github.com/caolan/async
> http://webapplog.com/seven-things-you-should-stop-doing-with-node-js/
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/burritos/scaffolding-angular/pull/2#issuecomment-204738932>
>



-- 
With regards,
N.Thillai Arasu
H/P:+91-9840460487

**Comment by eduardogch** [comment]
screenshot from 2016-04-02 12 21 10

Fixed it! let me know about the async and if it is good, made the Pull request to master and publish a new version.

PD, it is weekend I know! but for me this is fun :D

**Pull request merged**
